<a href="https://colab.research.google.com/github/derrickgreenspan/COT5600/blob/master/hw_1_problem_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 1 ##

### Problem 2 ###

**Some definitions**

Let 

$$M\in\mathbb{R}^{n\times n}$$ be an arbitrary matrix.  

Let $$p(x)=a_0 + a_1 x + a_2 x^2 + \ldots + a_n x^n \in\mathbb{R}[x]$$ be an arbitrary polynomial of less or equal to $n$.

The above polynomial can be used to define a matrix function that takes matrices as input and outputs matrices as follows: 

$$p(M) = a_0 I + a_1 M + \ldots + a_n M^n,$$ 

that is, each monomial $x^k$ is substituted by the corresponding matrix power $M^k$.

We say that a polynomial $p(x)$ annihilates a matrix $M\in\mathbb{R}^{n\times n}$ iff $p(M)=\boldsymbol{0}$, where $\boldsymbol{0}$ is the zero matrix.

**Task**

The task is to write a function ```annihilate_poly``` that takes as input an arbitrary square numpy array $M$ and outputs a vector whose cofficients are the coefficients of a (non-trivial) polynomial that annihilates $M$.  Non-trivial means that its is not the zero polynomial which maps every matrix to the zero matrix.

**Hint**

You can reduce the problem to finding a linear dependance relationship between the $n+1$ vectors 

$$\mathrm{vec}(I), \mathrm{vec}(M), \mathrm{vec}(M^2),\ldots,\mathrm{vec}(M^n)\in\mathrm{R}^{n^2}.$$



The operation $\mathrm{vec}$ turns a square matrix $M\in\mathbb{R}^{n\times n}$ into a vector $v\in\mathbb{R}^{n^2}$ by first listing the entries of the first row, then those of the second row etc.

Update: 

To solve this problem, you have to compute the null space of the matrix $A\in \mathbb{R}^{n^2\times (n+1)}$ whose columns are the vectors $\mathrm{vec}(M^k)$ for $k\in\{0,\ldots,n\}$.

In [0]:
# Found this very useful: https://www.geeksforgeeks.org/null-space-and-nullity-of-a-matrix/

import numpy as np
import scipy as sp
from scipy import linalg as la

def vec(array): # See here https://stackoverflow.com/questions/25248290/most-elegant-implementation-of-matlabs-vec-function-in-numpy
  return array.flatten("F") #array.T.reshape((1, -1), order="F") 

def get_A_column(array, deg): # Probably should name this something better...
  return np.array(vec(np.linalg.matrix_power(array, deg))).T

def get_A_matrix(array, deg):
  matrix = get_A_column(array, 0)
  for i in range(1, deg):
    matrix = np.append(matrix, vec(np.linalg.matrix_power(array, i)).T, axis=1)
  return matrix

def get_null_space(array, deg):
  matrix = get_A_matrix(array, deg+1)
  return la.null_space(matrix)

def annhilate_poly(array, deg):
  if array.shape[0] != array.shape[1]:
    return
  matrix = get_null_space(array, deg)
  return np.flip(matrix.T)

**Task**

Write a function ```annihilate_min_deg_poly``` that computes a non-trivial polynomial that annihilates a given square matrix and has the smallest possible degree.  Recall that a polynomial $p(x)$ has degree $d$ if the coefficient $a_{d+1}=\ldots=a_n=0$.

In [0]:
def annhilate_min_deg_poly(array):
    if array.shape[0] != array.shape[1]:
        print("This matrix is not a square matrix and thus cannot be annihilated")
        return
    degree = array.shape[0]
    for i in range(0, degree+1):
        if(annhilate_poly(array, i).size) != 0:
            return annhilate_poly(array, i), i    
    print("There is no non-trivial polynomial that annihlates the given matrix")
    return

**Test cases:**

---

X Matrix: 

    0 1
    1 0

Result: 



```
(array([[-0.70710678,  0.        ,  0.70710678]]), 2)
```
(Minimal degree 2, the minimum annhilating polynomial is: ${-1 \over \sqrt(2)} x^2 + {1 \over \sqrt(2)}$)


Basic Matrix:

    1 2
    3 4

Result:

```
(array([[-0.18257419,  0.91287093,  0.36514837]]), 2)
```

(Minimal degree 2, the minimum annhilating polynomial is: $-0.18257419x^2 + 0.91287093x + 0.36514837$ )

A matrix less than its degree:  (Found here: http://math.kangwon.ac.kr/~yhpark/webla/lin-alg/node5.html)

    5 -6 -6
    -1 4 2
    3 -6 -4

Result:

```
(array([[-0.26726124,  0.80178373, -0.53452248]]), 2)
```

(Minimal degree 2, the minimum annhilating polynomial is: $-0.26726124x^2 + 0.80178373x - 0.53452248 $ )




