<a href="https://colab.research.google.com/github/derrickgreenspan/COT5600/blob/master/Quantum_computing_hw_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 3

### Problem 1 

Let $\omega=\mathrm{exp}(2\pi i/N)$ be the $N$th root of unity.  The Fourier matrix of size $N$ is the matrix $F_N=(q_{k,\ell})\in\mathbb{C}^{N\times N}$ whose entries are given by
$$q_{k,\ell}=\frac{1}{\sqrt{N}} \omega^{k \cdot \ell}$$ for $k, \ell \in \{0,\ldots,N-1\}$.

Using numpy, implement the function ```get_fourier_matrix``` that create the Fourier matrix of size $N$.

Compute the eigenvalues of eigenvectors of the Fourier matrix.  

To check that your code is correct, you should verify that the Fourier matrix is unitary and that its eigenvalues are $N$th roots of unity.

In [3]:
import numpy as np
def get_fourier_matrix(N):
  omega = np.exp((2*np.pi*1j)/N)
  normalizer = 1/np.sqrt(N)
  return np.asarray([[normalizer*omega**(j*i) for i in range(N)] for j in range(N)])

def check_if_unitary(f): # From https://stackoverflow.com/questions/34997244/is-there-a-way-in-numpy-to-test-whether-a-matrix-is-unitary (link given to me by Justin Gosselin)
  return np.allclose(np.eye(len(f)), f.dot(f.T.conj()))  


# Test output
size = 4
fourier_matrix_size_4 = get_fourier_matrix(size)
if(check_if_unitary(fourier_matrix_size_10)):
  print("The matrix of size", size, "is unitary")
else:
  printf("The matrix of size", size, "is not unitary")


# Let's try another one
size = 10
fourier_matrix_size_10 = get_fourier_matrix(size)

if(check_if_unitary(fourier_matrix_size_10)):
  print("The matrix of size", size, "is unitary")
else:
  printf("The matrix of size", size, "is not unitary")




The matrix of size 4 is unitary
The matrix of size 10 is unitary


**Cyclic shift matrix**

The cyclic shift matrix is the matrix $P_N=(p_{k,\ell}\in\mathbb{C}^{N\times N})$
 whose entries are given by

$$ p_{k,\ell} = 1 \mbox{ if } \ell = k + 1 \pmod{N} $$

$$ p_{k,\ell} = 0 \mbox{ if } \ell \neq k + 1 \pmod{N} $$

Using numpy, implement the function ```get_cyclic_shift_matrix``` that create the cyclic shift matrix of size $N$.

Compute the eigenvalues of $P_N$.

To show that your code is correct, you should verify the following properties:

- the cyclic shift matrix is unitary
- the $N$th power of the cyclic shift matrix is the identity matrix
- the eigenvalues of the cyclic shift matrix are $N$th roots of unity
- the cyclic shift matrix is diagonalized by the Fourier matrix, that is, $F_N^\dagger P_N F_N$ is diagonal.

In [53]:
from numpy import linalg as la

def get_cyclic_shift_matrix(N):
  p = np.empty((N,N), dtype=int)
  for i in range(N):
    for j in range(N):
      if(j == ((i+1)%N)):
        p[i][j] = 1
      else:
        p[i][j] = 0
        
  return np.asarray(p)

cyclic_shift_size_4 = get_cyclic_shift_matrix(4)
print(cyclic_shift_size_4)
verify(cyclic_shift_size_4, 4)

def verify(shift_matrix, N):
  if(check_if_unitary(shift_matrix)):
    print("Cyclic shift matrix of size", N, "is unitary!")
  else:
    print("Cyclic shift matrix of size", N, "is not unitary!")

  if(np.allclose(np.eye(len(cyclic_shift_size_4)),
                la.matrix_power(cyclic_shift_size_4, 4))):
    print("When raised to the", N,"th power", "the cyclic shift matrix of size",
          N, "is the identity matrix")
  else:
    print("When raised to the", N,"th power", "the cyclic shift matrix of size",
          N, "is not the identity matrix")

  if(np.allclose((la.eig(shift_matrix[0])**N), 1)):
    print("The eigenvalues of the cyclic shift matrix of size", N, "are the",
          N,"th roots of unity")

  


[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]
Cyclic shift matrix of size 4 is unitary!
When raised to the 4 th power the cyclic shift matrix of size 4 is the identity matrix


NameError: ignored

### Problem 2

Using Qiskit IBM Q Experience, implement the quantum phase estimation circuit with 3-bit precision.  

This quantum circuit is explained on pages 110-113 (Inverse Fourier transform for 3 qubits) of the lecture slides.

You can preprare the initial state using ```u3``` gates. See [u3 gates](https://qiskit.org/documentation/tutorials/fundamentals/5_summary_of_quantum_operations.html?highlight=arbitrary%20single%20qubit%20gate#u-gates)

The controlled $R_2^\dagger$ gates are controlled ```u3``` gates.  See [controlled u3 gate](https://qiskit.org/documentation/tutorials/fundamentals/5_summary_of_quantum_operations.html?highlight=arbitrary%20single%20qubit%20gate#Controlled-u3-rotation).

In [0]:
%matplotlib inline
# Importing standard Qiskit libraries and configuring account
from qiskit import QuantumCircuit, execute, Aer, IBMQ, ClassicalRegister, QuantumRegister, execute
from qiskit.compiler import transpile, assemble
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer
from qiskit.tools.jupyter import *
from qiskit.visualization import *
# Loading your IBM Q account(s)
provider = IBMQ.load_account()

import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi


backend = BasicAer.get_backend('unitary_simulator')

def prepare_init_state(circuit, theta):
  circuit.x(3)


# Inspired by the information in the qiskit textbook found here: https://qiskit.org/textbook/ch-algorithms/quantum-phase-estimation.html#2.-Example:-T-gate-
q = QuantumRegister(3)
qc = QuantumCircuit(q)
qc.h(0)
qc.cu3(pi/2, pi/2, pi/2, q[0], q[1])
qc.h(1)
qc.cu3(pi/2, pi/2, pi/2, q[0], q[2])
qc.cu3(pi/2, pi/2, pi/2, q[1], q[2])
qc.h(2)
qc.draw()